# Generated by Django 4.1.3 on 2022-11-13 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_college_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='college_name',
            new_name='collegename',
        ),
    ]
